version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-pedidos
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedidos
    ports:
      - "5432:5432"
    networks:
      - network-pedidos

  mongo:
    image: mongo:6
    container_name: mongo-pedidos
    ports:
      - "27017:27017"
    networks:
      - network-pedidos

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-pedidos
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - network-pedidos

  pedido-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedido-service
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - network-pedidos
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-pedidos:5432/pedidos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongo-pedidos:27017/pedidos
      SPRING_RABBITMQ_HOST: rabbitmq-pedidos

networks:
  network-pedidos:
    external: true