spring:
  application:
    name: pedido

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/pedidos
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/pedidos

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

server:
  port: 8080
  servlet:
    context-path: /pedido

logging:
  level:
    root: OFF
    org.springframework.web: OFF
    br.com.fiap.pedido: OFF